version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-optics
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optics
      MYSQL_USER: optics_user
      MYSQL_PASSWORD: optics_pass
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: