version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-optica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optica
      MYSQL_USER: optica_user
      MYSQL_PASSWORD: optica_pass
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: