version: "3.8"

services:
  mysql-optics:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-optics
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optics
      MYSQL_USER: optics_user
      MYSQL_PASSWORD: optics_pass
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data_optics:/var/lib/mysql

  mysql-pizzeria:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-pizzeria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzeria
      MYSQL_USER: pizzeria_user
      MYSQL_PASSWORD: pizzeria_pass
    ports:
      - "3307:3306"   # diferente puerto para evitar conflicto con optics
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data_pizzeria:/var/lib/mysql

volumes:
  mysql_data_optics:
  mysql_data_pizzeria:
